---
title: "dashboard_hw"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(p8105.datasets)

library(plotly)
```


```{r}
data("instacart")

hour_df = 
  instacart %>% 
  filter(product_name == "Pink Lady Apples")%>% 
  group_by(product_name,order_dow) %>% 
  summarize(mean_order_time = round(mean(order_hour_of_day))) %>% 
  mutate(
    order_dow = c("0" = "Sunday", "1" = "Monday", "2" = "Tuesday", "3" = "Wednesday", "4" ="Thursday", "5" = "Friday", "6" = "Saturday" )
  )
colnames(hour_df) = c("product","day","mean_order_time")


```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}


#sample = sample_n(instacart,1000)

instacart %>% 
  group_by(aisle) %>%
  summarise(number = n()) %>%
  filter(number > 10000) %>% 
   mutate(
     aisle = factor(aisle),
     aisle = fct_reorder(aisle, number)
   ) %>% 
  plot_ly(
    x = ~aisle, y = ~number, type = "scatter", mode = "markers", alpha = 0.5)
   


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r,warning=FALSE,message=FALSE}
 instacart %>% 
   filter(aisle == "packaged vegetables fruits") %>% 
   group_by(aisle,product_name) %>% 
   summarise(order_count = n()) %>% 
  filter(order_count > 1000) %>% 
    plot_ly(x = ~aisle, y = ~order_count, color = ~aisle, type = "box",colors = "viridis")
  
  
```

### Chart C

```{r, warning=FALSE,message=FALSE}
  
hour_df %>%  
    plot_ly(x = ~day, y = ~mean_order_time,  type = "bar")
  
```

```{r}
#rmarkdown::render("dashboard_hw.Rmd", output_format= "flexdashboard::flex_dashboard")

```
